apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: incriproject
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: incriproject
      tier: db
  template:
    metadata:
      labels:
        app: incriproject
        tier: db
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                  - incriproject
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "incriproject"
          effect: "NoSchedule"
      containers:
        - name: redis
          image: redis:7-alpine
          command: ["redis-server", "--appendonly", "yes"]
          ports:
            - containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 20
          volumeMounts:
            - name: redis-storage
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
