version: "2.39.0"
services:
  web:
    build: .
    container_name: incre-app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - incre-app-network

  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      incre-app-network:

networks:
  incre-app-network:
    driver: bridge

