version: "2.39.0"
services:
  web:
    build: .
    container_name: incri-app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"