apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: incriproject

spec:
  replicas: 5
  selector:
    matchLabels:
      app: incriproject
      tier: backend
  template:
    metadata:
      labels:
        app: incriproject
        tier: backend
    
    spec:
      containers:
        - name: web-container
          image: incriprojectacr.azurecr.io/incriproject:latest
          ports:
            - containerPort: 5000
          envFrom:
          - configMapRef:
             name: redis-config
          
          resources:
            requests:
              cpu: 50m
              memory: "128Mi"
            limits:
              cpu: 200m
              memory: "256Mi"
      readinessProbe:
          httpGet:
            path: /
            port: 5000