apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: incriproject
spec:
  type: LoadBalancer
  selector:
    app: incriproject
    tier: backend
  ports:
    - port: 80
      targetPort: 5000
