apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: incriproject

spec:
  selector:
    matchLabels:
      app: incriproject
      tier: backend
  template:
    metadata:
      labels:
        app: incriproject
    
    spec:
      containers:
        - name: web-container
          image: incriprojectacr.azurecr.io/
          ports:
            - containerPort: 5000
          envFrom:
            - configMape:
              name: redis-config
          
          resources:
            requests:
              cpu: 50m
              memory: "128Mi"
            limits:
              cpu: 200m
              memory: "256Mi"